---

- name: clone webapp
  hosts: g1
  become: yes

  tasks:
  - name: Install required python
    yum:
      name: python3
      state: present

  - name: install git
    yum:
      name: git
      state: present


  - name: host code
    git:
      repo: https://github.com/Morjay007/flask_webapp.git
      dest: /var/www/html/
      force: yes

...